name: checks

on:
  workflow_call:

jobs:
  fmt-job:
    name: Format check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python environment
      uses: ./.github/actions/python-env

    - name: Bootstrap
      run: |
        poetry install

    - name: Run black
      run: |
        poetry run black --check .

  ut-job:
    name: Unittests (python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python environment
      uses: ./.github/actions/python-env
      with:
        python-version: ${{ matrix.python-version }}

    - name: Bootstrap
      run: |
        poetry install --sync

    - name: Run pytest
      run: |
        poetry run pytest --verbose
